language: c

script: asdf plugin-test k9s $TRAVIS_BUILD_DIR --asdf-tool-version v0.13.6

before_script:
  - git clone --branch master --depth=1 https://github.com/asdf-vm/asdf.git asdf
  - source asdf/asdf.sh

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - jq

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew install jq; fi
